name: autofix.ci

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1.20.0
        with:
          cache: true
      - run: vp check --fix
        continue-on-error: true
      - run: vp exec knip --fix
        continue-on-error: true
      - run: vp config
      - name: Run autofix.ci
        uses: autofix-ci/action@v1
        with:
          commit-message: 'refactor: apply automatic fixes'
