name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1.15.0
        with:
          cache: true
      - run: vp check
      - run: vp test --coverage
      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
      - run: vp exec knip
      - run: vp pack
      - run: vp run validate-api
