on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - name: Checkout Git repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v7

      - name: Setup Vite+
        if: ${{ steps.release.outputs.release_created }}
        uses: voidzero-dev/setup-vp@v1.20.0
        with:
          cache: true

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: vp pack

      - name: Generate TSDoc metadata
        if: ${{ steps.release.outputs.release_created }}
        run: vp run validate-api

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm publish --provenance --access public
